name: Foo Application CD Pipeline

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  bucket:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-east-1

      - name: Save SSH Private Key
        run: |
          echo "${{ secrets.FOO_SSH_PRIVATE_KEY }}" > infra/foo_ec2_key
          chmod 600 infra/foo_ec2_key

      - name: Save SSH Public Key
        run: |
          echo "${{ secrets.FOO_SSH_PUBLIC_KEY }}" > infra/foo_ec2_key.pub
      
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
      
      - name: Initialise Terraform
        run: |
          cd bucket/
          terraform init

      - name: Validate Terraform
        run: |
          cd bucket/
          terraform validate

      - name: Check if S3 bucket exists
        id: check_s3
        run: |
          BUCKET_NAME="foo-bucket-s3895662-s4077402"

          if aws s3 ls "s3://$BUCKET_NAME" > /dev/null 2>&1; then
            echo "S3 bucket $BUCKET_NAME already exists. Skipping creation."
            echo "s3_bucket_exists=true" >> $GITHUB_ENV
          else
            echo "S3 bucket $BUCKET_NAME does not exist. Will create it."
            echo "s3_bucket_exists=false" >> $GITHUB_ENV
          fi

      - name: Check if DynamoDB table exists
        id: check_dynamodb
        run: |
          TABLE_NAME="foostatelock"

          if aws dynamodb describe-table --table-name $TABLE_NAME > /dev/null 2>&1; then
            echo "DynamoDB table $TABLE_NAME already exists. Skipping creation."
            echo "dynamodb_table_exists=true" >> $GITHUB_ENV
          else
            echo "DynamoDB table $TABLE_NAME does not exist. Will create it."
            echo "dynamodb_table_exists=false" >> $GITHUB_ENV
          fi

      - name: Apply Terraform
        if: env.s3_bucket_exists == 'false' || env.dynamodb_table_exists == 'false'
        run: |
          cd bucket/
          terraform apply --auto-approve
  
  infra:
    runs-on: ubuntu-latest
    needs: bucket

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-east-1

      - name: Save SSH Private Key
        run: |
          echo "${{ secrets.FOO_SSH_PRIVATE_KEY }}" > infra/foo_ec2_key
          chmod 600 infra/foo_ec2_key

      - name: Save SSH Public Key
        run: |
          echo "${{ secrets.FOO_SSH_PUBLIC_KEY }}" > infra/foo_ec2_key.pub
      
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Install Ansible
        run: pipx install ansible
      
      - name: Initialise Terraform
        run: |
          cd infra/
          terraform init

      - name: Validate Terraform
        run: |
          cd infra/
          terraform validate

      - name: Check if Terraform state file exists in S3
        id: check_state
        run: |
          BUCKET_NAME="foo-bucket-s3895662-s4077402"
          STATE_FILE="terraform.tfstate"

          # Check if the state file exists in the S3 bucket
          if aws s3 ls s3://$BUCKET_NAME/state/$STATE_FILE > /dev/null 2>&1; then
            echo "Terraform state file exists. Checking if infrastructure is already deployed."

            # Download the state file for inspection
            aws s3 cp s3://$BUCKET_NAME/state/$STATE_FILE ./terraform.tfstate

            # Check if the state file has any resources (i.e., infrastructure is deployed)
            resources=$(jq '.resources | length' terraform.tfstate)

            if [ "$resources" -gt 0 ]; then
              echo "Infrastructure is already deployed. Stopping the pipeline."
              exit 1
            else
              echo "No infrastructure found in the state file. Proceeding with Terraform."
            fi
          else
            echo "No Terraform state file found. Proceeding with Terraform."
          fi

      - name: Apply Terraform
        run: |
          cd infra/
          terraform apply --auto-approve

      - name: Sleep for 30 seconds
        run: |
          echo "The oven is warming up the SSH port...Please wait approximately 30 seconds (sorry)"
          sleep 30

      - name: Run DB playbook
        run: ansible-playbook ansible/db-playbook.yml -i infra/ansible-inventory.yml --private-key=infra/foo_ec2_key

      - name: Run APP playbook
        run: ansible-playbook ansible/app-playbook.yml -i infra/ansible-inventory.yml --private-key=infra/foo_ec2_key

      


